### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [SamSanai/VoiceMaster-Discord-Bot#10]
Your discord bot is disconnected...

Could you fix this?

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
![image](https://user-images.githubusercontent.com/20026629/83070317-9893f680-a06b-11ea-8428-3a024a3c8844.png)

The issue has not been fixed, so why you closed the ticket?
This is not the first time that the bot will definitely disconnect.
Each time I have to delete the channel, to reinvite the bot, reset the category channel, reset all the permissions for each channel in the cateogy and reset the bot.

So, could you fix this or just stop to disconnect the bot and sto creating new one each time? Or I don't know 👍 thanks in advance for what u are doing constantly for us.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
The issue has not been fixed
bot still disconnect

**Comment by SamSanai** [comment]
You've been told this already if you're having an issue with the bots uptime join our discord server and make a ticket.
