### ISSUE TITLE
Bot is Disconnected

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [SamSanai/VoiceMaster-Discord-Bot#11]
Your discord bot is disconnected...

Could you fix this?

![image](https://user-images.githubusercontent.com/20026629/83070317-9893f680-a06b-11ea-8428-3a024a3c8844.png)

I have already told you.... here:
[https://github.com/SamSanai/VoiceMaster-Discord-Bot/issues/10](url)
The issue has not been fixed, so, why you closed the ticket?
This is not the first time that the bot will definitely disconnect.
Each time I have to delete the channel, to reinvite the bot, reset the category channel, reset all the permissions for each channel in the cateogy and reset the bot.

So, could you fix this or just stop to disconnect the bot and sto creating new one each time? Or I don't know 👍 thanks in advance for what u are doing constantly for us.

Today the bot is still offline

**Comment by Androz2091** [comment]
In general, the fact that a bot is disconnected or not is not necessarily a code problem. Moreover, the owner is probably already aware of this (so he's either already working on it or he doesn't have time) and this repository seems to me to be a bad place to report this kind of problem.
You can probably ask for more information directly on Discord.

**Comment by SamSanai** [comment]
The bot you've mentioned was a placeholder bot while I was rewriting the main bot.
Invite the actual bot using :
https://discord.com/oauth2/authorize?client_id=472911936951156740&scope=bot&permissions=288374865
And as Androz mentioned you should probably join our support discord server to stay up to date with our changelogs/updates etc:
https://discord.gg/y9pgpbt
