### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by ghost** [SamSanai/VoiceMaster-Discord-Bot#15]
Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'

**Comment by kasepta** [comment]
hello @SamSanai we need your help

**Comment by SamSanai** [comment]
I need more of the traceback.

**Comment by kasepta** [comment]
i'm not change anything, just put the token. 
and when use command .voice setup
get the error log : Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
@SamSanai

**Comment by SamSanai** [comment]
As I mentioned before I need to see more of the traceback. Show me more of the error you get so I can locate the issue.

**Comment by kasepta** [comment]
how to traceback? i don't understand @SamSanai

**Comment by SamSanai** [comment]
Show me more of the error, when you get that error copy the error from the terminal I can't guess where the issue is I need to see where the issue is.

**Comment by kasepta** [comment]
when i run command ```.voice setup```
i got this error log :
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\xxx\Desktop\VoiceMaster-Discord-Bot-master> py voicecreate.py
Logged in as
Bot     
7557436431757476142
------
Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
```
@SamSanai

**Comment by SamSanai** [comment]
Are you using the command in the bots private messages?

**Comment by SamSanai** [comment]
#17
