### ISSUE TITLE
Error on line 25

### ISSUE THREAD

**Issue by NokaAngel** [SamSanai/VoiceMaster-Discord-Bot#16]
```
  File "voicecreate.py", line 25
    print('Failed to load extension {extension}.', file=sys.stderr)
                                                       ^
SyntaxError: invalid syntax

```

Using Ubuntu 18.04.

**Comment by SamSanai** [comment]
Hmm I don't see what's wrong with it other than the fact that you've taken out the fstring
print(f'Failed to load extension {extension}.', file=sys.stderr)

**Comment by NokaAngel** [comment]
f string in or not @SamSanai it still errors.

**Comment by SamSanai** [comment]
Not sure mate, you'd have better luck asking discord.gg/python
