### ISSUE TITLE
VoiceMaster disconnected

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [SamSanai/VoiceMaster-Discord-Bot#18]
hello

the bot VoiceMaster#9351
 is disconnected...

![image](https://user-images.githubusercontent.com/20026629/96323021-b1517880-101b-11eb-8c49-ccfeadc206ed.png)

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
https://github.com/SamSanai/VoiceMaster-Discord-Bot/issues/10

**Comment by SamSanai** [comment]
You've been told this already if you're having an issue with the bots uptime join our discord server and make a ticket.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Check your discord. I've already wrote in your discord. And the bit is still disconnected.
