### ISSUE TITLE
I cant setup the bot in my server 

### ISSUE THREAD

**Issue by cc6s** [SamSanai/VoiceMaster-Discord-Bot#19]
![visual studio](https://user-images.githubusercontent.com/72402287/106134916-e10e3180-616f-11eb-86f8-fc3926b9f154.jpg)

**Comment by Tim232** [comment]
which command was used when the error occured?

**Comment by Tim232** [comment]
as i guess in cogs/voice.py  there is `ctx.guild.owner,id` in line 100 and 137, 
it makes the error because the code doesnt have the bot's intent
you need to change in voicecreate.py
`bot = commands.Bot(command_prefix=".", intents=discord.Intents.all())`

**Comment by TomabGH** [comment]
> as i guess in cogs/voice.py there is `ctx.guild.owner,id` in line 100 and 137,
> it makes the error because the code doesnt have the bot's intent
> you need to change in voicecreate.py
> `bot = commands.Bot(command_prefix=".", intents=discord.Intents.all())`

This didn't work for me:
![image](https://user-images.githubusercontent.com/67195101/111513601-41bdf180-8751-11eb-9122-dd76cdaaaf40.png)

What can i do?

**Comment by Tim232** [comment]
The error says that you need to enable intents on the developer portal
maybe you can enable it at [here](https://discordpy.readthedocs.io/en/latest/intents.html) 
you need to check both member and presence to use discord.Intents.all()

**Comment by Tim232** [comment]
actually u can just do 
```python
intents=discord.Intents.default()
intents.member=True
bot = commands.Bot(command_prefix='!', intents=intents)
```
like this if you only enable members

**Comment by TomabGH** [comment]
> actually u can just do
> 
> ```python
> intents=discord.Intents.default()
> intents.member=True
> bot = commands.Bot(command_prefix='!', intents=intents)
> ```
> 
> like this if you only enable members

Well then I'll have to contact support for this as my bot was already approved some time ago....
Thank you for the help!

**Comment by Tim232** [comment]
i hope you get a good result
