### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by wahyu02501** [SamSanai/VoiceMaster-Discord-Bot#20]
![2B910FFF-76BB-4F57-B4C7-BC7690AF4384](https://user-images.githubusercontent.com/75318896/107182740-4687db00-6a18-11eb-8a6d-104a2b64ee7c.png)

**Comment by Tim232** [comment]
whats the problem

**Comment by wahyu02501** [comment]
problem according to the picture

**Comment by Tim232** [comment]
uhh.. you mean you cannot find the code? you can see the code by clicking the code icon on the left bottom

**Comment by SamSanai** [comment]
No response
