### ISSUE TITLE
Help me pls(

### ISSUE THREAD

**Issue by ghost** [SamSanai/VoiceMaster-Discord-Bot#21]
![image](https://user-images.githubusercontent.com/52193360/112159350-1ed08900-8bfa-11eb-9414-b90c856eb96c.png)

**Comment by Tim232** [comment]
its becuz the running bot's token is wrong
```python
DISCORD_TOKEN = 'Enter Discord Token here'
```

you need to enter your token there

**Comment by SamSanai** [comment]
Answered.
