### ISSUE TITLE
Can't delete a channel

### ISSUE THREAD

**Issue by DozoLozo** [SamSanai/VoiceMaster-Discord-Bot#28]
Hi!

Some time ago someone created a voice channel on my server, however, it didn't delete itself after emptying. What's even worse, it can't be deleted nor moved by any means - tried kicking VoiceMaster out of the server, resetting it, changing permissions on said channel, deleting a category where the channel once was (it just moved it to the top of the server). Neither server Admin nor creator of the channel can't delete it.

Is there any way to delete the channel?

**Comment by SamSanai** [comment]
Hi there Dozo, that's an issue related to Discord the channel shouldn't be there but Discord hasn't registered it yet. There are two options one wait it out until it registers that the channel is deleted or send over a support ticket to discord and they'll deal with it for you.

**Comment by DozoLozo** [comment]
Okay, thanks! Already tried contacting support, will try again then
