### ISSUE TITLE
Invalid channel names allow for users to sit in the join to create vc indefinetely

### ISSUE THREAD

**Issue by Oman395** [SamSanai/VoiceMaster-Discord-Bot#43]
Title pretty much says it. If you use the /voice name command with an invalid name (for example U+000, �), the bot will be unable to make the channel, or rename it. I'm not quite sure how the API responds but I imagine it throws an error-- as such, the bot will except out, and leave you in the vc indefinitely. Obviously, this isn't a huge issue, but it could potentially cause issues down the line-- if this were somehow able to except out of the code, before it started listening for the person to leave, then it would leave behind the channel.

There are two easy fixes that I can think of; either just throw in an extra bit of logic to handle invalid channel names, or implement some form of filtering to the /channel name command.

**Comment by SamSanai** [comment]
The open-source version of the bot is behind on a lot of features, as I've mentioned in the description of this repo it won't receive any updates outside of keeping the bot functional in the state it currently is in.
