### ISSUE TITLE
Some bugs and ideas

### ISSUE THREAD

**Issue by deellaydev** [SamSanai/VoiceMaster-Discord-Bot#44]
1. When you close the room while being in the channel, you automatically lose trust to your own room. And you can't do anything in the channel anymore. Not at all. You have to recreate it in order to regain trust beforehand and close the room again.

2. When, for example, you close the room and leave it (disconnect), the room settings are not saved. When creating a new room, it is open, even though I closed it before. Only the participant limit in the room is saved.

**Comment by SamSanai** [comment]
1. Has been resolved in 39f6bccceafe2a33e3d6bd34e2ec1a50e44e85df
2. Is intended.
