### ISSUE TITLE
Errors whie starting the bot

### ISSUE THREAD

**Issue by xFlum3** [SamSanai/VoiceMaster-Discord-Bot#47]
Trying to install this discord bot but when i start the bot i got this errors:
```
root@discord-bots:~/VoiceMaster-Discord-Bot# python3 voicecreate.py 
Logged in as
FlumeZ Auto Voice Channel
97902
------
/usr/local/lib/python3.8/dist-packages/discord/ext/commands/bot.py:618: RuntimeWarning: coroutine 'setup' was never awaited
  setup(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Failed to load extension cogs.voice.
Traceback (most recent call last):
  File "voicecreate.py", line 28, in on_ready
    await bot.load_extension(extension)
TypeError: object NoneType can't be used in 'await' expression
```
How can i fix it ?

**Comment by xFlum3** [comment]
**UPDATE:**
I updated the discord.py version to 2+ but now when i use the command .setup i got this errors:
![image](https://github.com/SamSanai/VoiceMaster-Discord-Bot/assets/35439776/5a607472-a2dc-41cf-a372-fd657a34b99a)
But .help command working.

**Comment by SamSanai** [comment]
The command you're looking for is `.voice setup` as the error mentions `setup` isn't a command.
