### ISSUE TITLE
Request member Reject List

### ISSUE THREAD

**Issue by malekymm** [SamSanai/VoiceMaster-Discord-Bot#48]
### **Feature Description**
Feature for member has been rejected in temp voice to easily permit them someday.

### **Why do you want this feature ?**
Because in big server there is a lot of trolling so need to reject them, but sometimes I reject wrong username. Also, the temp voice not just for a day but can last for 3–5 day.

**Comment by SamSanai** [comment]
They can be permitted back in to the channel using `.voice permit`.
